OrdererOrgs:
  - Name: orderer
    Domain: vdoservices.in
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer.iinrg
        SANS: 
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer.fpo1
        SANS: 
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer.fpo2
        SANS: 
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: iinrg
    Domain: iinrg.vdoservices.in
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: fpo1
    Domain: fpo1.vdoservices.in
    EnableNodeOUs: true
    # Specs:
    #   - Hostname: fpo1
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: fpo2
    Domain: fpo2.vdoservices.in
    EnableNodeOUs: true
    # Specs:
    #   - Hostname: fpo2
    Template:
      Count: 2
    Users:
      Count: 1